### ISSUE TITLE
Core dumped error when running control flow commands

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/inspect4py#320]
See for example:
```
code_inspector -i ../test_repos/somef -o test_dir -cf
```
Output:
```
Creating cf /home/dgarijo/Documents/GitHub/code_inspector/test_dir/somef/control_flow
Creating jsDir:test_dir/somef/json_files
Creating cf /home/dgarijo/Documents/GitHub/code_inspector/test_dir/experiments/control_flow
Creating jsDir:test_dir/experiments/json_files
Creating cf /home/dgarijo/Documents/GitHub/code_inspector/test_dir/helper_scripts/control_flow
Creating jsDir:test_dir/helper_scripts/json_files
Segmentation fault (core dumped)
```

The problem is that the script fails silently and stops with the rest. It's ok if it fails, but it should continue processing the rest of the files.

**Comment by rosafilgueira** [comment]
Dindt get that error : code_inspector -i ../test_repos/somef -o test_dir -cf
<img width="797" alt="Screen Shot 2022-01-24 at 12 30 30" src="https://user-images.githubusercontent.com/6940078/150783312-46558f4f-ddc9-4793-835e-2727c5d86b78.png">

**Comment by dgarijo** [comment]
Further inspection of this issue uncovered that `cdmcfparser` 2.3.2 is not supported for Python>=3.9. The newest version is `cdmcfparser` 2.2.3, which is causing the error. 

I will open a separate issue to address this problem.
