### ISSUE TITLE
Typo: should be a '.', not a '*'

### ISSUE THREAD

**Issue by OEG-Clark** [SoftwareUnderstanding/inspect4py#352]
https://github.com/SoftwareUnderstanding/inspect4py/blob/3ed30dd219dbcb079151906cd68d7556d56fc383/inspect4py/cli.py#L339

**Comment by dgarijo** [comment]
The issue is not completed, as no PR has been merged yet.
I also don't understand why this is an issue very well. Do you mind explaining?
