### ISSUE TITLE
Potential bug when inspecting directories

### ISSUE THREAD

**Issue by lazyhope** [SoftwareUnderstanding/inspect4py#365]
In line 1252:https://github.com/SoftwareUnderstanding/inspect4py/blob/60622d1064e925bab57b01e7a0ab5511d4d2433a/inspect4py/cli.py#L1250-L1253 we are using the subdirectory's base name as the output subdirectory name. For example, when inspecting `Chowlk`, we have the json files of all python file under `Chowlk/` stored in `<output>/Chowlk/json_files/`, then we have the json files of all python file under `Chowlk/source/chowlk/` stored in `<output>/chowlk/json_files/`.

However, if we have two subdirectory of the same name this could be a problem, for example, if we have both `Chowlk/source/chowlk/` and `Chowlk/source/sub/chowlk/`, as they cannot be stored in the same output path `<output>/chowlk/json_files/` the latter one is going to be ignored in line 1166:https://github.com/SoftwareUnderstanding/inspect4py/blob/60622d1064e925bab57b01e7a0ab5511d4d2433a/inspect4py/cli.py#L1164-L1171

Also, when running inspect4py on MacOS, since the operating system path is not case-sensitive, when inspecting `Chowlk`, the output of `Chowlk/source/chowlk/` is already ignored, as python consider `<output>/chowlk/json_files/` already exists when it is actually `<output>/Chowlk/json_files/` being created before. Hence there is not json files under `Chowlk/source/chowlk/` in the output directory

**Comment by dgarijo** [comment]
This is fixed according to https://github.com/lazyhope/inspect4py/commit/3cc63ba75fdcc19eba92b08da9ad00e8897814eb
