### ISSUE TITLE
Error in extracting functions

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/inspect4py#409]
In this project: https://github.com/oeg-upm/Chowlk 

I see this file: https://github.com/oeg-upm/Chowlk/blob/webservice/converter.py which has a `main` function, a `body` and a `print_errors` function. 
However, when I ran inspect4py I find the following: 
![image](https://user-images.githubusercontent.com/1520666/219750194-9c64d1d5-442e-4b07-ac4a-1dc2d5eb86fc.png)

There is no `print_errors` and the `transform_ontology` function is not declared in this file, it's imported. I think the problem is that the function is imported like this: `from source.chowlk.transformations import transform_ontology` and therefore inspect4py thinks it's a local function, when it isn't

What I don't understand is why `print_errors` is deleted.

**Comment by rosafilgueira** [comment]
I have run **inspect4py -i Chowlk -o Chowlk_out -cl -si -html -sc**  And I got a different output for converter.   I just goint open  **Chowlk/json_files/converter.json** . See here:

![Uploading Screenshot 2023-02-17 at 19.41.13.png…]()
<img width="1512" alt="Screenshot 2023-02-17 at 19 41 24" src="https://user-images.githubusercontent.com/6940078/219757607-db62a936-aeb3-4310-93b2-540bd485f88d.png">
<img width="1512" alt="Screenshot 2023-02-17 at 19 41 31" src="https://user-images.githubusercontent.com/6940078/219757620-f324420a-7e60-4ad6-a471-6020a65f30b8.png">

**Comment by rosafilgueira** [comment]
Just going to put the screenshot for the functions and body - of converters.json. You can see that I get the printer_errors, and I dont get the transform_ontology: 

<img width="1512" alt="Screenshot 2023-02-17 at 19 41 24" src="https://user-images.githubusercontent.com/6940078/219758604-fb69d173-e6d5-4db6-8c0a-4a235c438950.png">
<img width="1486" alt="Screenshot 2023-02-17 at 19 41 13" src="https://user-images.githubusercontent.com/6940078/219758626-cd073ed0-edcc-4abb-81b4-ef4d0fbe9ad8.png">

**Comment by dgarijo** [comment]
The problem is that I ran it on an old version of the code, where there is a `transform_ontology` and there is no `printer_errors` function. But then I looked into the latest version of the repo to verify everything.

My bad, `inspect4py` is working appropriately. I'll close the issue/
