### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by OEG-Clark** [SoftwareUnderstanding/inspect4py#415]
[Index Error In Testing](https://github.com/SoftwareUnderstanding/inspect4py/blob/9da8fe5779436fc54556956243dce31692678ee8/inspect4py/parse_setup_files.py#L59)
Should Be: 
cs_string = cs[1].strip().replace('\'', '').split('["')[1]

**Comment by dgarijo** [comment]
Thanks. Can you please indicate which repo leads to an error, and which
error it produces?

**Comment by OEG-Clark** [comment]
The Error happened in testing in the repo of Somef

**Comment by dgarijo** [comment]
Fixed now in your PR
