### ISSUE TITLE
IndexError While processing Folders

### ISSUE THREAD

**Issue by OEG-Clark** [SoftwareUnderstanding/inspect4py#420]
https://github.com/SoftwareUnderstanding/inspect4py/blob/21da57df3173c7a3ed84faefb5861cf748866d79/inspect4py/cli.py#L1321

The code will read to L1329, and jump to expect line

Error: Error when processing test_google.py:  (<class ‘KeyError’>, KeyError(‘source_code’), <traceback object at 0x7ff4924f3c00>)

**Comment by dgarijo** [comment]
Without additional information, it's not clear what the error is. I can't reproduce it locally, as all files seem to be working fine.
```
env_inspect4py_3.9) dgarijo@pop-os:~/Documents/GitHub/inspect4py$ inspect4py --input_path ../test_repos/Chowlk/ -ast -sc -df
Analysis completed
Total number of folders processed (root folder is considered a folder): 3
Total number of files found:  10
Total number of classes found:  4
Total number of dependencies found in those files 69
Total number of functions parsed:  28
```
